begin;

create table if not exists public.formulario_7_bioensayo_intake (
  intake_id bigint generated by default as identity primary key,
  review_status text not null default 'pending'
    check (review_status in ('pending', 'reviewed', 'rejected')),
  review_notes text,
  reviewed_by text,
  reviewed_at timestamptz,
  formulario_codigo text not null default 'F7' check (formulario_codigo = 'F7'),
  formulario_nombre text not null default 'Registro de datos del bioensayo de la botella CDC',
  fecha_registro date not null default current_date,
  nombre_poblacion text not null,
  id_proyecto text not null,
  modalidad_bioensayo text not null
    constraint formulario_7_modalidad_bioensayo_check check (modalidad_bioensayo in ('Exploratorio', 'Completa')),
  dosis_diagnostica_1x boolean not null,
  dosis_intensidad text check (dosis_intensidad in ('1X', '2X', '5X', '10X')),
  sinergista_def boolean not null default false,
  sinergista_pbo boolean not null default false,
  sinergista_dm boolean not null default false,
  codigo_bioensayo text not null,
  fecha_realizacion_bioensayo date not null,
  codigo_insecticida text not null,
  solvente_utilizado text not null check (solvente_utilizado in ('Etanol', 'Otro')),
  solvente_otro text,
  dosis_ug_ml numeric not null check (dosis_ug_ml >= 0),
  codigo_dosis text not null,
  fecha_revestimiento_botellas date not null,
  numero_usos_botella_e1 integer check (numero_usos_botella_e1 >= 0),
  numero_usos_botella_e2 integer check (numero_usos_botella_e2 >= 0),
  numero_usos_botella_e3 integer check (numero_usos_botella_e3 >= 0),
  numero_usos_botella_e4 integer check (numero_usos_botella_e4 >= 0),
  numero_usos_botella_c1 integer check (numero_usos_botella_c1 >= 0),
  origen_material text not null check (origen_material in ('Silvestre', 'Laboratorio')),
  codigo_pais text not null,
  edad_dias integer check (edad_dias >= 0),
  edad_indefinida boolean not null default false,
  codigo_especie_mosquito text not null,
  poblacion_material text not null,
  hora_separacion time not null,
  generacion_filial text,
  generacion_filial_indefinida boolean not null default false,
  fecha_separacion date not null,
  codigo_responsable_revestimiento text not null,
  codigo_responsable_bioensayo text not null,
  codigo_control_calidad text not null,
  codigo_revision_24h text not null,
  temperatura_inicial_c numeric not null,
  temperatura_final_c numeric not null,
  humedad_relativa_inicial_pct numeric not null
    check (humedad_relativa_inicial_pct between 0 and 100),
  humedad_relativa_final_pct numeric not null
    check (humedad_relativa_final_pct between 0 and 100),
  hora_inicio_bioensayo time not null,
  hora_final_bioensayo time not null,
  fuente_formulario text,
  creado_por text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint formulario_7_tipo_bioensayo_consistente check (
    (
      modalidad_bioensayo = 'Exploratorio'
      and not dosis_diagnostica_1x
      and dosis_intensidad is null
      and not sinergista_def and not sinergista_pbo and not sinergista_dm
    )
    or (
      modalidad_bioensayo = 'Completa'
      and (
        (
          dosis_diagnostica_1x
          and dosis_intensidad is null
          and not sinergista_def and not sinergista_pbo and not sinergista_dm
        )
        or (
          not dosis_diagnostica_1x
          and dosis_intensidad is not null
          and not sinergista_def and not sinergista_pbo and not sinergista_dm
        )
        or (
          not dosis_diagnostica_1x
          and dosis_intensidad is null
          and (sinergista_def or sinergista_pbo or sinergista_dm)
        )
      )
    )
  ),
  constraint formulario_7_solvente_consistente check (
    (solvente_utilizado = 'Etanol' and nullif(btrim(solvente_otro), '') is null)
    or (solvente_utilizado = 'Otro' and nullif(btrim(solvente_otro), '') is not null)
  ),
  constraint formulario_7_edad_consistente check (
    (edad_indefinida and edad_dias is null)
    or (not edad_indefinida and edad_dias is not null)
  ),
  constraint formulario_7_generacion_consistente check (
    (generacion_filial_indefinida and nullif(btrim(generacion_filial), '') is null)
    or (not generacion_filial_indefinida and nullif(btrim(generacion_filial), '') is not null)
  )
);

create table if not exists public.formulario_7_bioensayo_resultado_intake (
  resultado_id bigint generated by default as identity primary key,
  intake_id bigint not null references public.formulario_7_bioensayo_intake(intake_id) on delete cascade,
  fase text not null check (fase in ('bioensayo', 'kdr_24h', 'control_calidad')),
  botella text not null check (botella in ('b1', 'b2', 'b3', 'b4', 'c1', 'c2')),
  tiempo_minutos integer not null check (tiempo_minutos in (0, 15, 30, 45, 1440)),
  hora_lectura time,
  vivos integer not null check (vivos >= 0),
  incapacitados integer not null check (incapacitados >= 0),
  creado_en timestamptz not null default now(),
  unique (intake_id, fase, botella, tiempo_minutos),
  constraint formulario_7_fase_tiempo_consistente check (
    (fase = 'bioensayo' and tiempo_minutos in (0, 15, 30, 45))
    or (fase = 'kdr_24h' and tiempo_minutos = 1440)
    or (fase = 'control_calidad' and tiempo_minutos in (0, 15, 30, 45, 1440))
  )
);

create table if not exists public.formulario_7_bioensayo_comentario_intake (
  comentario_id bigint generated by default as identity primary key,
  intake_id bigint not null references public.formulario_7_bioensayo_intake(intake_id) on delete cascade,
  orden integer not null check (orden between 1 and 4),
  comentario text not null,
  nombre text,
  creado_en timestamptz not null default now(),
  unique (intake_id, orden)
);

create index if not exists formulario_7_intake_review_status_idx
  on public.formulario_7_bioensayo_intake (review_status, creado_en desc);
create index if not exists formulario_7_intake_codigo_idx
  on public.formulario_7_bioensayo_intake (codigo_bioensayo);
create index if not exists formulario_7_intake_fecha_idx
  on public.formulario_7_bioensayo_intake (fecha_realizacion_bioensayo);
create index if not exists formulario_7_resultado_intake_id_idx
  on public.formulario_7_bioensayo_resultado_intake (intake_id);
create index if not exists formulario_7_comentario_intake_id_idx
  on public.formulario_7_bioensayo_comentario_intake (intake_id);

alter table public.formulario_7_bioensayo_intake enable row level security;
alter table public.formulario_7_bioensayo_resultado_intake enable row level security;
alter table public.formulario_7_bioensayo_comentario_intake enable row level security;

drop policy if exists formulario_7_intake_deny_anon on public.formulario_7_bioensayo_intake;
create policy formulario_7_intake_deny_anon
  on public.formulario_7_bioensayo_intake for all to anon using (false) with check (false);
drop policy if exists formulario_7_intake_deny_authenticated on public.formulario_7_bioensayo_intake;
create policy formulario_7_intake_deny_authenticated
  on public.formulario_7_bioensayo_intake for all to authenticated using (false) with check (false);

drop policy if exists formulario_7_resultado_deny_anon on public.formulario_7_bioensayo_resultado_intake;
create policy formulario_7_resultado_deny_anon
  on public.formulario_7_bioensayo_resultado_intake for all to anon using (false) with check (false);
drop policy if exists formulario_7_resultado_deny_authenticated on public.formulario_7_bioensayo_resultado_intake;
create policy formulario_7_resultado_deny_authenticated
  on public.formulario_7_bioensayo_resultado_intake for all to authenticated using (false) with check (false);

drop policy if exists formulario_7_comentario_deny_anon on public.formulario_7_bioensayo_comentario_intake;
create policy formulario_7_comentario_deny_anon
  on public.formulario_7_bioensayo_comentario_intake for all to anon using (false) with check (false);
drop policy if exists formulario_7_comentario_deny_authenticated on public.formulario_7_bioensayo_comentario_intake;
create policy formulario_7_comentario_deny_authenticated
  on public.formulario_7_bioensayo_comentario_intake for all to authenticated using (false) with check (false);

revoke all on table public.formulario_7_bioensayo_intake from anon, authenticated;
revoke all on table public.formulario_7_bioensayo_resultado_intake from anon, authenticated;
revoke all on table public.formulario_7_bioensayo_comentario_intake from anon, authenticated;
revoke all on sequence public.formulario_7_bioensayo_intake_intake_id_seq from anon, authenticated;
revoke all on sequence public.formulario_7_bioensayo_resultado_intake_resultado_id_seq from anon, authenticated;
revoke all on sequence public.formulario_7_bioensayo_comentario_intake_comentario_id_seq from anon, authenticated;

comment on table public.formulario_7_bioensayo_intake is
  'Encabezado de ingresos pendientes de Formulario 7 (bioensayo de botella CDC).';
comment on table public.formulario_7_bioensayo_resultado_intake is
  'Lecturas normalizadas por fase, botella y tiempo para Formulario 7.';
comment on table public.formulario_7_bioensayo_comentario_intake is
  'Comentarios numerados asociados a un ingreso de Formulario 7.';

commit;
