begin;

create table if not exists public.formulario_1_ovitrampa_intake (
  intake_id bigint generated by default as identity primary key,
  review_status text not null default 'pending'
    check (review_status in ('pending', 'reviewed', 'rejected')),
  review_notes text,
  reviewed_by text,
  reviewed_at timestamptz,

  formulario_codigo text not null default 'F1' check (formulario_codigo = 'F1'),
  formulario_nombre text not null default 'Colocacion y retiro de ovitrampa',
  fecha_registro date not null default current_date,
  pais text not null default 'El Salvador'
    check (pais in ('El Salvador', 'Guatemala')),
  id_institucion text not null default 'UVG',
  departamento text,
  municipio text,
  ciclo text not null,
  ronda text,
  codigo_formulario text,

  fecha_colocacion date not null,
  grupo_responsable_colocacion text,
  cuadrante text not null,
  codigo_casa text not null,
  latitud numeric,
  longitud numeric,
  codigo_gps text,
  ovitrampas_colocadas integer not null check (ovitrampas_colocadas > 0),
  fecha_retiro date,
  grupo_responsable_retiro text,
  responsable_retiro_nombre text,
  ovitrampas_retiradas integer check (ovitrampas_retiradas >= 0),
  retiro_buen_estado integer not null default 0 check (retiro_buen_estado >= 0),
  retiro_sin_agua integer not null default 0 check (retiro_sin_agua >= 0),
  retiro_sin_sustrato integer not null default 0 check (retiro_sin_sustrato >= 0),
  retiro_sin_ovitrampa integer not null default 0 check (retiro_sin_ovitrampa >= 0),
  retiro_movida integer not null default 0 check (retiro_movida >= 0),
  retiro_volteada integer not null default 0 check (retiro_volteada >= 0),
  retiro_casa_cerrada integer not null default 0 check (retiro_casa_cerrada >= 0),
  retiro_casa_cerrada_descripcion text,

  fuente_formulario text,
  creado_por text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),

  constraint formulario_1_fechas_chk
    check (fecha_retiro is null or fecha_colocacion <= fecha_retiro),
  constraint formulario_1_latitud_chk
    check (latitud is null or latitud between -90 and 90),
  constraint formulario_1_longitud_chk
    check (longitud is null or longitud between -180 and 180),
  constraint formulario_1_retiro_colocadas_chk
    check (ovitrampas_retiradas is null or ovitrampas_retiradas <= ovitrampas_colocadas),
  constraint formulario_1_retiro_estado_total_chk
    check (
      (
        retiro_buen_estado +
        retiro_sin_agua +
        retiro_sin_sustrato
      ) <= coalesce(ovitrampas_retiradas, ovitrampas_colocadas)
    ),
  constraint formulario_1_retiro_estado_colocadas_chk
    check (
      (
        retiro_buen_estado +
        retiro_sin_agua +
        retiro_sin_sustrato +
        retiro_sin_ovitrampa +
        retiro_movida +
        retiro_volteada +
        retiro_casa_cerrada
      ) <= ovitrampas_colocadas
    ),
  constraint formulario_1_retiro_cero_estado_chk
    check (
      ovitrampas_retiradas is null
      or ovitrampas_retiradas <> 0
      or (
        retiro_buen_estado +
        retiro_sin_agua +
        retiro_sin_sustrato +
        retiro_sin_ovitrampa +
        retiro_movida +
        retiro_volteada +
        retiro_casa_cerrada
      ) = ovitrampas_colocadas
    )
);

create table if not exists public.formulario_1_ovitrampa_detalle_intake (
  detalle_id bigint generated by default as identity primary key,
  intake_id bigint not null
    references public.formulario_1_ovitrampa_intake(intake_id)
    on delete cascade,

  codigo_sustrato text not null,
  creado_en timestamptz not null default now()
);

create unique index if not exists formulario_1_detalle_sustrato_unique_idx
  on public.formulario_1_ovitrampa_detalle_intake (intake_id, codigo_sustrato);

create index if not exists formulario_1_intake_review_status_idx
  on public.formulario_1_ovitrampa_intake (review_status, creado_en desc);
create index if not exists formulario_1_intake_fecha_idx
  on public.formulario_1_ovitrampa_intake (fecha_colocacion, fecha_retiro);
create index if not exists formulario_1_detalle_intake_id_idx
  on public.formulario_1_ovitrampa_detalle_intake (intake_id);
create index if not exists formulario_1_intake_ubicacion_idx
  on public.formulario_1_ovitrampa_intake (cuadrante, codigo_casa);
create index if not exists formulario_1_intake_gps_idx
  on public.formulario_1_ovitrampa_intake (codigo_gps);

alter table public.formulario_1_ovitrampa_intake enable row level security;
alter table public.formulario_1_ovitrampa_detalle_intake enable row level security;

drop policy if exists formulario_1_intake_deny_anon
  on public.formulario_1_ovitrampa_intake;
create policy formulario_1_intake_deny_anon
  on public.formulario_1_ovitrampa_intake
  for all to anon
  using (false)
  with check (false);

drop policy if exists formulario_1_intake_deny_authenticated
  on public.formulario_1_ovitrampa_intake;
create policy formulario_1_intake_deny_authenticated
  on public.formulario_1_ovitrampa_intake
  for all to authenticated
  using (false)
  with check (false);

drop policy if exists formulario_1_detalle_deny_anon
  on public.formulario_1_ovitrampa_detalle_intake;
create policy formulario_1_detalle_deny_anon
  on public.formulario_1_ovitrampa_detalle_intake
  for all to anon
  using (false)
  with check (false);

drop policy if exists formulario_1_detalle_deny_authenticated
  on public.formulario_1_ovitrampa_detalle_intake;
create policy formulario_1_detalle_deny_authenticated
  on public.formulario_1_ovitrampa_detalle_intake
  for all to authenticated
  using (false)
  with check (false);

revoke all on table public.formulario_1_ovitrampa_intake from anon, authenticated;
revoke all on table public.formulario_1_ovitrampa_detalle_intake from anon, authenticated;
revoke all on sequence public.formulario_1_ovitrampa_intake_intake_id_seq from anon, authenticated;
revoke all on sequence public.formulario_1_ovitrampa_detalle_intake_detalle_id_seq from anon, authenticated;

comment on table public.formulario_1_ovitrampa_intake is
  'Encabezado de ingresos pendientes de Formulario 1: colocacion y retiro de ovitrampa.';
comment on table public.formulario_1_ovitrampa_detalle_intake is
  'Detalle normalizado de sustratos asociados a un ingreso de Formulario 1.';

commit;
