begin;

create table public.formulario_7_bioensayo_comentario_intake_new (
  comentario_id bigint generated by default as identity primary key,
  intake_id bigint not null references public.formulario_7_bioensayo_intake(intake_id) on delete cascade,
  comentario text not null,
  nombre text,
  creado_en timestamptz not null default now(),
  unique (intake_id)
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'formulario_7_bioensayo_comentario_intake'
      and column_name = 'orden'
  ) then
    insert into public.formulario_7_bioensayo_comentario_intake_new (intake_id, comentario, nombre, creado_en)
    select distinct on (intake_id)
      intake_id,
      comentario,
      nombre,
      creado_en
    from public.formulario_7_bioensayo_comentario_intake
    where nullif(btrim(comentario), '') is not null
    order by intake_id, orden nulls first, comentario_id;
  else
    insert into public.formulario_7_bioensayo_comentario_intake_new (intake_id, comentario, nombre, creado_en)
    select distinct on (intake_id)
      intake_id,
      comentario,
      nombre,
      creado_en
    from public.formulario_7_bioensayo_comentario_intake
    where nullif(btrim(comentario), '') is not null
    order by intake_id, comentario_id;
  end if;
end $$;

drop table public.formulario_7_bioensayo_comentario_intake cascade;
alter table public.formulario_7_bioensayo_comentario_intake_new
  rename to formulario_7_bioensayo_comentario_intake;
alter index public.formulario_7_bioensayo_comentario_intake_new_pkey
  rename to formulario_7_bioensayo_comentario_intake_pkey;
alter index public.formulario_7_bioensayo_comentario_intake_new_intake_id_key
  rename to formulario_7_bioensayo_comentario_intake_intake_id_key;
alter sequence public.formulario_7_bioensayo_comentario_intake_new_comentario_id_seq
  rename to formulario_7_bioensayo_comentario_intake_comentario_id_seq;

create index formulario_7_comentario_intake_id_idx
  on public.formulario_7_bioensayo_comentario_intake (intake_id);

alter table public.formulario_7_bioensayo_comentario_intake enable row level security;

create policy formulario_7_comentario_deny_anon
  on public.formulario_7_bioensayo_comentario_intake for all to anon using (false) with check (false);
create policy formulario_7_comentario_deny_authenticated
  on public.formulario_7_bioensayo_comentario_intake for all to authenticated using (false) with check (false);

revoke all on table public.formulario_7_bioensayo_comentario_intake from anon, authenticated;
revoke all on sequence public.formulario_7_bioensayo_comentario_intake_comentario_id_seq from anon, authenticated;

comment on table public.formulario_7_bioensayo_comentario_intake is
  'Un comentario asociado a un ingreso de Formulario 7.';

commit;
