begin;

create table if not exists public.catalogo_ubicacion_departamento (
  pais text not null,
  codigo_pais text not null,
  codigo_departamento text not null,
  departamento text not null,
  actualizado_en timestamptz not null default now(),
  primary key (pais, codigo_departamento),
  unique (codigo_pais, codigo_departamento)
);

create table if not exists public.catalogo_ubicacion_municipio (
  pais text not null,
  codigo_pais text not null,
  codigo_departamento text not null,
  codigo_municipio text not null,
  municipio text not null,
  actualizado_en timestamptz not null default now(),
  primary key (pais, codigo_municipio),
  unique (codigo_pais, codigo_municipio),
  foreign key (pais, codigo_departamento)
    references public.catalogo_ubicacion_departamento (pais, codigo_departamento)
    on update cascade on delete restrict
);

delete from public.catalogo_ubicacion_municipio where pais in ('Guatemala', 'El Salvador');
delete from public.catalogo_ubicacion_departamento where pais in ('Guatemala', 'El Salvador');

insert into public.catalogo_ubicacion_departamento (pais, codigo_pais, codigo_departamento, departamento)
values
  ('Guatemala', 'GT', '01', 'Guatemala'),
  ('Guatemala', 'GT', '02', 'El Progreso'),
  ('Guatemala', 'GT', '03', 'Sacatepéquez'),
  ('Guatemala', 'GT', '04', 'Chimaltenango'),
  ('Guatemala', 'GT', '05', 'Escuintla'),
  ('Guatemala', 'GT', '06', 'Santa Rosa'),
  ('Guatemala', 'GT', '07', 'Sololá'),
  ('Guatemala', 'GT', '08', 'Totonicapán'),
  ('Guatemala', 'GT', '09', 'Quetzaltenango'),
  ('Guatemala', 'GT', '10', 'Suchitepéquez'),
  ('Guatemala', 'GT', '11', 'Retalhuleu'),
  ('Guatemala', 'GT', '12', 'San Marcos'),
  ('Guatemala', 'GT', '13', 'Huehuetenango'),
  ('Guatemala', 'GT', '14', 'Quiché'),
  ('Guatemala', 'GT', '15', 'Baja Verapaz'),
  ('Guatemala', 'GT', '16', 'Alta Verapaz'),
  ('Guatemala', 'GT', '17', 'Petén'),
  ('Guatemala', 'GT', '18', 'Izabal'),
  ('Guatemala', 'GT', '19', 'Zacapa'),
  ('Guatemala', 'GT', '20', 'Chiquimula'),
  ('Guatemala', 'GT', '21', 'Jalapa'),
  ('Guatemala', 'GT', '22', 'Jutiapa'),
  ('El Salvador', 'SV', '01', 'Ahuachapán'),
  ('El Salvador', 'SV', '02', 'Santa Ana'),
  ('El Salvador', 'SV', '03', 'Sonsonate'),
  ('El Salvador', 'SV', '04', 'Chalatenango'),
  ('El Salvador', 'SV', '05', 'La Libertad'),
  ('El Salvador', 'SV', '06', 'San Salvador'),
  ('El Salvador', 'SV', '07', 'Cuscatlán'),
  ('El Salvador', 'SV', '08', 'La Paz'),
  ('El Salvador', 'SV', '09', 'Cabañas'),
  ('El Salvador', 'SV', '10', 'San Vicente'),
  ('El Salvador', 'SV', '11', 'Usulután'),
  ('El Salvador', 'SV', '12', 'San Miguel'),
  ('El Salvador', 'SV', '13', 'Morazán'),
  ('El Salvador', 'SV', '14', 'La Unión')
on conflict (pais, codigo_departamento) do update set
  codigo_pais = excluded.codigo_pais,
  departamento = excluded.departamento,
  actualizado_en = now();

insert into public.catalogo_ubicacion_municipio (pais, codigo_pais, codigo_departamento, codigo_municipio, municipio)
values
  ('Guatemala', 'GT', '01', '0101', 'Guatemala'),
  ('Guatemala', 'GT', '01', '0102', 'Santa Catarina Pinula'),
  ('Guatemala', 'GT', '01', '0103', 'San José Pinula'),
  ('Guatemala', 'GT', '01', '0104', 'San José del Golfo'),
  ('Guatemala', 'GT', '01', '0105', 'Palencia'),
  ('Guatemala', 'GT', '01', '0106', 'Chinautla'),
  ('Guatemala', 'GT', '01', '0107', 'San Pedro Ayampuc'),
  ('Guatemala', 'GT', '01', '0108', 'Mixco'),
  ('Guatemala', 'GT', '01', '0109', 'San Pedro Sacatepéquez'),
  ('Guatemala', 'GT', '01', '0110', 'San Juan Sacatepéquez'),
  ('Guatemala', 'GT', '01', '0111', 'San Raymundo'),
  ('Guatemala', 'GT', '01', '0112', 'Chuarrancho'),
  ('Guatemala', 'GT', '01', '0113', 'Fraijanes'),
  ('Guatemala', 'GT', '01', '0114', 'Amatitlán'),
  ('Guatemala', 'GT', '01', '0115', 'Villa Nueva'),
  ('Guatemala', 'GT', '01', '0116', 'Villa Canales'),
  ('Guatemala', 'GT', '01', '0117', 'San Miguel Petapa'),
  ('Guatemala', 'GT', '02', '0201', 'Guastatoya'),
  ('Guatemala', 'GT', '02', '0202', 'Morazán'),
  ('Guatemala', 'GT', '02', '0203', 'San Agustín Acasaguastlán'),
  ('Guatemala', 'GT', '02', '0204', 'San Cristóbal Acasaguastlán'),
  ('Guatemala', 'GT', '02', '0205', 'El Jícaro'),
  ('Guatemala', 'GT', '02', '0206', 'Sansare'),
  ('Guatemala', 'GT', '02', '0207', 'Sanarate'),
  ('Guatemala', 'GT', '02', '0208', 'San Antonio La Paz'),
  ('Guatemala', 'GT', '03', '0301', 'Antigua'),
  ('Guatemala', 'GT', '03', '0302', 'Jocotenango'),
  ('Guatemala', 'GT', '03', '0303', 'Pastores'),
  ('Guatemala', 'GT', '03', '0304', 'Sumpango'),
  ('Guatemala', 'GT', '03', '0305', 'Santo Domingo Xenacoj'),
  ('Guatemala', 'GT', '03', '0306', 'Santiago Sacatepéquez'),
  ('Guatemala', 'GT', '03', '0307', 'San Bartolomé Milpas Altas'),
  ('Guatemala', 'GT', '03', '0308', 'San Lucas Sacatepéquez'),
  ('Guatemala', 'GT', '03', '0309', 'Santa Lucía Milpas Altas'),
  ('Guatemala', 'GT', '03', '0310', 'Magdalena Milpas Altas'),
  ('Guatemala', 'GT', '03', '0311', 'Santa María de Jesús'),
  ('Guatemala', 'GT', '03', '0312', 'Ciudad Vieja'),
  ('Guatemala', 'GT', '03', '0313', 'San Miguel Dueñas'),
  ('Guatemala', 'GT', '03', '0314', 'Alotenango'),
  ('Guatemala', 'GT', '03', '0315', 'San Antonio Aguas Calientes'),
  ('Guatemala', 'GT', '03', '0316', 'Santa Catarina Barahona'),
  ('Guatemala', 'GT', '04', '0401', 'Chimaltenango'),
  ('Guatemala', 'GT', '04', '0402', 'San José Poaquil'),
  ('Guatemala', 'GT', '04', '0403', 'San Martín Jilotepeque'),
  ('Guatemala', 'GT', '04', '0404', 'San Juan Comalapa'),
  ('Guatemala', 'GT', '04', '0405', 'Santa Apolonia'),
  ('Guatemala', 'GT', '04', '0406', 'Tecpán Guatemala'),
  ('Guatemala', 'GT', '04', '0407', 'Patzún'),
  ('Guatemala', 'GT', '04', '0408', 'San Miguel Pochuta'),
  ('Guatemala', 'GT', '04', '0409', 'Patzicía'),
  ('Guatemala', 'GT', '04', '0410', 'Santa Cruz Balanyá'),
  ('Guatemala', 'GT', '04', '0411', 'Acatenango'),
  ('Guatemala', 'GT', '04', '0412', 'San Pedro Yepocapa'),
  ('Guatemala', 'GT', '04', '0413', 'San Andrés Itzapa'),
  ('Guatemala', 'GT', '04', '0414', 'Parramos'),
  ('Guatemala', 'GT', '04', '0415', 'Zaragoza'),
  ('Guatemala', 'GT', '04', '0416', 'El Tejar'),
  ('Guatemala', 'GT', '05', '0501', 'Escuintla'),
  ('Guatemala', 'GT', '05', '0502', 'Santa Lucía Cotzumalguapa'),
  ('Guatemala', 'GT', '05', '0503', 'La Democracia'),
  ('Guatemala', 'GT', '05', '0504', 'Siquinalá'),
  ('Guatemala', 'GT', '05', '0505', 'Masagua'),
  ('Guatemala', 'GT', '05', '0506', 'Tiquisate'),
  ('Guatemala', 'GT', '05', '0507', 'La Gomera'),
  ('Guatemala', 'GT', '05', '0508', 'Guanagazapa'),
  ('Guatemala', 'GT', '05', '0509', 'San José'),
  ('Guatemala', 'GT', '05', '0510', 'Iztapa'),
  ('Guatemala', 'GT', '05', '0511', 'Palín'),
  ('Guatemala', 'GT', '05', '0512', 'San Vicente Pacaya'),
  ('Guatemala', 'GT', '05', '0513', 'Nueva Concepción'),
  ('Guatemala', 'GT', '06', '0601', 'Cuilapa'),
  ('Guatemala', 'GT', '06', '0602', 'Barberena'),
  ('Guatemala', 'GT', '06', '0603', 'Santa Rosa de Lima'),
  ('Guatemala', 'GT', '06', '0604', 'Casillas'),
  ('Guatemala', 'GT', '06', '0605', 'San Rafael Las Flores'),
  ('Guatemala', 'GT', '06', '0606', 'Oratorio'),
  ('Guatemala', 'GT', '06', '0607', 'San Juan Tecuaco'),
  ('Guatemala', 'GT', '06', '0608', 'Chiquimulilla'),
  ('Guatemala', 'GT', '06', '0609', 'Taxisco'),
  ('Guatemala', 'GT', '06', '0610', 'Santa María Ixhuatán'),
  ('Guatemala', 'GT', '06', '0611', 'Guazacapán'),
  ('Guatemala', 'GT', '06', '0612', 'Santa Cruz Naranjo'),
  ('Guatemala', 'GT', '06', '0613', 'Pueblo Nuevo Viñas'),
  ('Guatemala', 'GT', '06', '0614', 'Nueva Santa Rosa'),
  ('Guatemala', 'GT', '07', '0701', 'Sololá'),
  ('Guatemala', 'GT', '07', '0702', 'San José Chacayá'),
  ('Guatemala', 'GT', '07', '0703', 'Santa María Visitación'),
  ('Guatemala', 'GT', '07', '0704', 'Santa Lucía Utatlán'),
  ('Guatemala', 'GT', '07', '0705', 'Nahualá'),
  ('Guatemala', 'GT', '07', '0706', 'Santa Catarina Ixtahuacán'),
  ('Guatemala', 'GT', '07', '0707', 'Santa Clara La Laguna'),
  ('Guatemala', 'GT', '07', '0708', 'Concepción'),
  ('Guatemala', 'GT', '07', '0709', 'San Andrés Semetabaj'),
  ('Guatemala', 'GT', '07', '0710', 'Panajachel'),
  ('Guatemala', 'GT', '07', '0711', 'Santa Catarina Palopó'),
  ('Guatemala', 'GT', '07', '0712', 'San Antonio Palopó'),
  ('Guatemala', 'GT', '07', '0713', 'San Lucas Tolimán'),
  ('Guatemala', 'GT', '07', '0714', 'Santa Cruz La Laguna'),
  ('Guatemala', 'GT', '07', '0715', 'San Pablo La Laguna'),
  ('Guatemala', 'GT', '07', '0716', 'San Marcos La Laguna'),
  ('Guatemala', 'GT', '07', '0717', 'San Juan La Laguna'),
  ('Guatemala', 'GT', '07', '0718', 'San Pedro La Laguna'),
  ('Guatemala', 'GT', '07', '0719', 'Santiago Atitlán'),
  ('Guatemala', 'GT', '08', '0801', 'Totonicapán'),
  ('Guatemala', 'GT', '08', '0802', 'San Cristóbal Totonicapán'),
  ('Guatemala', 'GT', '08', '0803', 'San Francisco El Alto'),
  ('Guatemala', 'GT', '08', '0804', 'San Andrés Xecul'),
  ('Guatemala', 'GT', '08', '0805', 'Momostenango'),
  ('Guatemala', 'GT', '08', '0806', 'Santa María Chiquimula'),
  ('Guatemala', 'GT', '08', '0807', 'Santa Lucía La Reforma'),
  ('Guatemala', 'GT', '08', '0808', 'San Bartolo Aguas Calientes'),
  ('Guatemala', 'GT', '09', '0901', 'Quetzaltenango'),
  ('Guatemala', 'GT', '09', '0902', 'Salcajá'),
  ('Guatemala', 'GT', '09', '0903', 'Olintepeque'),
  ('Guatemala', 'GT', '09', '0904', 'San Carlos Sija'),
  ('Guatemala', 'GT', '09', '0905', 'Sibilia'),
  ('Guatemala', 'GT', '09', '0906', 'Cabricán'),
  ('Guatemala', 'GT', '09', '0907', 'Cajolá'),
  ('Guatemala', 'GT', '09', '0908', 'San Miguel Sigüilá'),
  ('Guatemala', 'GT', '09', '0909', 'San Juan Ostuncalco'),
  ('Guatemala', 'GT', '09', '0910', 'San Mateo'),
  ('Guatemala', 'GT', '09', '0911', 'Concepción Chiquirichapa'),
  ('Guatemala', 'GT', '09', '0912', 'San Martín Sacatepéquez'),
  ('Guatemala', 'GT', '09', '0913', 'Almolonga'),
  ('Guatemala', 'GT', '09', '0914', 'Cantel'),
  ('Guatemala', 'GT', '09', '0915', 'Huitán'),
  ('Guatemala', 'GT', '09', '0916', 'Zunil'),
  ('Guatemala', 'GT', '09', '0917', 'Colomba Costa Cuca'),
  ('Guatemala', 'GT', '09', '0918', 'San Francisco La Unión'),
  ('Guatemala', 'GT', '09', '0919', 'El Palmar'),
  ('Guatemala', 'GT', '09', '0920', 'Coatepeque'),
  ('Guatemala', 'GT', '09', '0921', 'Génova Costa Cuca'),
  ('Guatemala', 'GT', '09', '0922', 'Flores Costa Cuca'),
  ('Guatemala', 'GT', '09', '0923', 'La Esperanza'),
  ('Guatemala', 'GT', '09', '0924', 'Palestina de Los Altos'),
  ('Guatemala', 'GT', '10', '1001', 'Mazatenango'),
  ('Guatemala', 'GT', '10', '1002', 'Cuyotenango'),
  ('Guatemala', 'GT', '10', '1003', 'San Francisco Zapotitlán'),
  ('Guatemala', 'GT', '10', '1004', 'San Bernardino'),
  ('Guatemala', 'GT', '10', '1005', 'San José El Ídolo'),
  ('Guatemala', 'GT', '10', '1006', 'Santo Domingo Suchitepéquez'),
  ('Guatemala', 'GT', '10', '1007', 'San Lorenzo'),
  ('Guatemala', 'GT', '10', '1008', 'Samayac'),
  ('Guatemala', 'GT', '10', '1009', 'San Pablo Jocopilas'),
  ('Guatemala', 'GT', '10', '1010', 'San Antonio Suchitepéquez'),
  ('Guatemala', 'GT', '10', '1011', 'San Miguel Panán'),
  ('Guatemala', 'GT', '10', '1012', 'San Gabriel'),
  ('Guatemala', 'GT', '10', '1013', 'Chicacao'),
  ('Guatemala', 'GT', '10', '1014', 'Patulul'),
  ('Guatemala', 'GT', '10', '1015', 'Santa Bárbara'),
  ('Guatemala', 'GT', '10', '1016', 'San Juan Bautista'),
  ('Guatemala', 'GT', '10', '1017', 'Santo Tomás La Unión'),
  ('Guatemala', 'GT', '10', '1018', 'Zunilito'),
  ('Guatemala', 'GT', '10', '1019', 'Pueblo Nuevo'),
  ('Guatemala', 'GT', '10', '1020', 'Río Bravo'),
  ('Guatemala', 'GT', '11', '1101', 'Retalhuleu'),
  ('Guatemala', 'GT', '11', '1102', 'San Sebastián'),
  ('Guatemala', 'GT', '11', '1103', 'Santa Cruz Muluá'),
  ('Guatemala', 'GT', '11', '1104', 'San Martín Zapotitlán'),
  ('Guatemala', 'GT', '11', '1105', 'San Felipe'),
  ('Guatemala', 'GT', '11', '1106', 'San Andrés Villa Seca'),
  ('Guatemala', 'GT', '11', '1107', 'Champerico'),
  ('Guatemala', 'GT', '11', '1108', 'Nuevo San Carlos'),
  ('Guatemala', 'GT', '11', '1109', 'El Asintal'),
  ('Guatemala', 'GT', '12', '1201', 'San Marcos'),
  ('Guatemala', 'GT', '12', '1202', 'San Pedro Sacatepéquez'),
  ('Guatemala', 'GT', '12', '1203', 'San Antonio Sacatepéquez'),
  ('Guatemala', 'GT', '12', '1204', 'Comitancillo'),
  ('Guatemala', 'GT', '12', '1205', 'San Miguel Ixtahuacán'),
  ('Guatemala', 'GT', '12', '1206', 'Concepción Tutuapa'),
  ('Guatemala', 'GT', '12', '1207', 'Tacaná'),
  ('Guatemala', 'GT', '12', '1208', 'Sibinal'),
  ('Guatemala', 'GT', '12', '1209', 'Tajumulco'),
  ('Guatemala', 'GT', '12', '1210', 'Tejutla'),
  ('Guatemala', 'GT', '12', '1211', 'San Rafael Pie de la Cuesta'),
  ('Guatemala', 'GT', '12', '1212', 'Nuevo Progreso'),
  ('Guatemala', 'GT', '12', '1213', 'El Tumbador'),
  ('Guatemala', 'GT', '12', '1214', 'San José El Rodeo'),
  ('Guatemala', 'GT', '12', '1215', 'Malacatán'),
  ('Guatemala', 'GT', '12', '1216', 'Catarina'),
  ('Guatemala', 'GT', '12', '1217', 'Ayutla (Tecún Umán)'),
  ('Guatemala', 'GT', '12', '1218', 'Ocós'),
  ('Guatemala', 'GT', '12', '1219', 'San Pablo'),
  ('Guatemala', 'GT', '12', '1220', 'El Quetzal'),
  ('Guatemala', 'GT', '12', '1221', 'La Reforma'),
  ('Guatemala', 'GT', '12', '1222', 'Pajapita'),
  ('Guatemala', 'GT', '12', '1223', 'Ixchiguán'),
  ('Guatemala', 'GT', '12', '1224', 'San José Ojetenam'),
  ('Guatemala', 'GT', '12', '1225', 'San Cristóbal Cucho'),
  ('Guatemala', 'GT', '12', '1226', 'Sipacapa'),
  ('Guatemala', 'GT', '12', '1227', 'Esquipulas Palo Gordo'),
  ('Guatemala', 'GT', '12', '1228', 'Río Blanco'),
  ('Guatemala', 'GT', '12', '1229', 'San Lorenzo'),
  ('Guatemala', 'GT', '13', '1301', 'Huehuetenango'),
  ('Guatemala', 'GT', '13', '1302', 'Chiantla'),
  ('Guatemala', 'GT', '13', '1303', 'Malacatancito'),
  ('Guatemala', 'GT', '13', '1304', 'Cuilco'),
  ('Guatemala', 'GT', '13', '1305', 'Nentón'),
  ('Guatemala', 'GT', '13', '1306', 'San Pedro Necta'),
  ('Guatemala', 'GT', '13', '1307', 'Jacaltenango'),
  ('Guatemala', 'GT', '13', '1308', 'San Pedro Soloma'),
  ('Guatemala', 'GT', '13', '1309', 'San Ildefonso Ixtahuacán'),
  ('Guatemala', 'GT', '13', '1310', 'Santa Bárbara'),
  ('Guatemala', 'GT', '13', '1311', 'La Libertad'),
  ('Guatemala', 'GT', '13', '1312', 'La Democracia'),
  ('Guatemala', 'GT', '13', '1313', 'San Miguel Acatán'),
  ('Guatemala', 'GT', '13', '1314', 'San Rafael La Independencia'),
  ('Guatemala', 'GT', '13', '1315', 'Todos Santos Cuchumatán'),
  ('Guatemala', 'GT', '13', '1316', 'San Juan Atitán'),
  ('Guatemala', 'GT', '13', '1317', 'Santa Eulalia'),
  ('Guatemala', 'GT', '13', '1318', 'San Mateo Ixtatán'),
  ('Guatemala', 'GT', '13', '1319', 'Colotenango'),
  ('Guatemala', 'GT', '13', '1320', 'San Sebastián Huehuetenango'),
  ('Guatemala', 'GT', '13', '1321', 'Tectitán'),
  ('Guatemala', 'GT', '13', '1322', 'Concepción Huista'),
  ('Guatemala', 'GT', '13', '1323', 'San Juan Ixcoy'),
  ('Guatemala', 'GT', '13', '1324', 'San Antonio Huista'),
  ('Guatemala', 'GT', '13', '1325', 'San Sebastián Coatán'),
  ('Guatemala', 'GT', '13', '1326', 'Santa Cruz Barillas'),
  ('Guatemala', 'GT', '13', '1327', 'Aguacatán'),
  ('Guatemala', 'GT', '13', '1328', 'San Rafael Petzal'),
  ('Guatemala', 'GT', '13', '1329', 'San Gaspar Ixchil'),
  ('Guatemala', 'GT', '13', '1330', 'Santiago Chimaltenango'),
  ('Guatemala', 'GT', '13', '1331', 'Santa Ana Huista'),
  ('Guatemala', 'GT', '13', '1332', 'Unión Cantinil'),
  ('Guatemala', 'GT', '14', '1401', 'Santa Cruz del Quiché'),
  ('Guatemala', 'GT', '14', '1402', 'Chiché'),
  ('Guatemala', 'GT', '14', '1403', 'Chinique'),
  ('Guatemala', 'GT', '14', '1404', 'Zacualpa'),
  ('Guatemala', 'GT', '14', '1405', 'Chajul'),
  ('Guatemala', 'GT', '14', '1406', 'Santo Tomás Chichicastenango'),
  ('Guatemala', 'GT', '14', '1407', 'Patzité'),
  ('Guatemala', 'GT', '14', '1408', 'San Antonio Ilotenango'),
  ('Guatemala', 'GT', '14', '1409', 'San Pedro Jocopilas'),
  ('Guatemala', 'GT', '14', '1410', 'Cunén'),
  ('Guatemala', 'GT', '14', '1411', 'San Juan Cotzal'),
  ('Guatemala', 'GT', '14', '1412', 'Joyabaj'),
  ('Guatemala', 'GT', '14', '1413', 'Nebaj'),
  ('Guatemala', 'GT', '14', '1414', 'San Andrés Sajcabajá'),
  ('Guatemala', 'GT', '14', '1415', 'San Miguel Uspantán'),
  ('Guatemala', 'GT', '14', '1416', 'Sacapulas'),
  ('Guatemala', 'GT', '14', '1417', 'San Bartolomé Jocotenango'),
  ('Guatemala', 'GT', '14', '1418', 'Canillá'),
  ('Guatemala', 'GT', '14', '1419', 'Chicamán'),
  ('Guatemala', 'GT', '14', '1420', 'Ixcán'),
  ('Guatemala', 'GT', '14', '1421', 'Pachalum'),
  ('Guatemala', 'GT', '15', '1501', 'Salamá'),
  ('Guatemala', 'GT', '15', '1502', 'San Miguel Chicaj'),
  ('Guatemala', 'GT', '15', '1503', 'Rabinal'),
  ('Guatemala', 'GT', '15', '1504', 'Cubulco'),
  ('Guatemala', 'GT', '15', '1505', 'Granados'),
  ('Guatemala', 'GT', '15', '1506', 'Santa Cruz El Chol'),
  ('Guatemala', 'GT', '15', '1507', 'San Jerónimo'),
  ('Guatemala', 'GT', '15', '1508', 'Purulhá'),
  ('Guatemala', 'GT', '16', '1601', 'Cobán'),
  ('Guatemala', 'GT', '16', '1602', 'Santa Cruz Verapaz'),
  ('Guatemala', 'GT', '16', '1603', 'San Cristóbal Verapaz'),
  ('Guatemala', 'GT', '16', '1604', 'Tactic'),
  ('Guatemala', 'GT', '16', '1605', 'Tamahú'),
  ('Guatemala', 'GT', '16', '1606', 'San Miguel Tucurú'),
  ('Guatemala', 'GT', '16', '1607', 'Panzós'),
  ('Guatemala', 'GT', '16', '1608', 'Senahú'),
  ('Guatemala', 'GT', '16', '1609', 'San Pedro Carchá'),
  ('Guatemala', 'GT', '16', '1610', 'San Juan Chamelco'),
  ('Guatemala', 'GT', '16', '1611', 'Lanquín'),
  ('Guatemala', 'GT', '16', '1612', 'Santa María Cahabón'),
  ('Guatemala', 'GT', '16', '1613', 'Chisec'),
  ('Guatemala', 'GT', '16', '1614', 'Chahal'),
  ('Guatemala', 'GT', '16', '1615', 'Fray Bartolomé de Las Casas'),
  ('Guatemala', 'GT', '16', '1616', 'La Tinta'),
  ('Guatemala', 'GT', '16', '1617', 'Raxruhá'),
  ('Guatemala', 'GT', '17', '1701', 'Flores'),
  ('Guatemala', 'GT', '17', '1702', 'San José'),
  ('Guatemala', 'GT', '17', '1703', 'San Benito'),
  ('Guatemala', 'GT', '17', '1704', 'San Andrés'),
  ('Guatemala', 'GT', '17', '1705', 'La Libertad'),
  ('Guatemala', 'GT', '17', '1706', 'San Francisco'),
  ('Guatemala', 'GT', '17', '1707', 'Santa Ana'),
  ('Guatemala', 'GT', '17', '1708', 'Dolores'),
  ('Guatemala', 'GT', '17', '1709', 'San Luis'),
  ('Guatemala', 'GT', '17', '1710', 'Sayaxché'),
  ('Guatemala', 'GT', '17', '1711', 'Melchor de Mencos'),
  ('Guatemala', 'GT', '17', '1712', 'Poptún'),
  ('Guatemala', 'GT', '18', '1801', 'Puerto Barrios'),
  ('Guatemala', 'GT', '18', '1802', 'Livingston'),
  ('Guatemala', 'GT', '18', '1803', 'El Estor'),
  ('Guatemala', 'GT', '18', '1804', 'Morales'),
  ('Guatemala', 'GT', '18', '1805', 'Los Amates'),
  ('Guatemala', 'GT', '19', '1901', 'Zacapa'),
  ('Guatemala', 'GT', '19', '1902', 'Estanzuela'),
  ('Guatemala', 'GT', '19', '1903', 'Río Hondo'),
  ('Guatemala', 'GT', '19', '1904', 'Gualán'),
  ('Guatemala', 'GT', '19', '1905', 'Teculután'),
  ('Guatemala', 'GT', '19', '1906', 'Usumatlán'),
  ('Guatemala', 'GT', '19', '1907', 'Cabañas'),
  ('Guatemala', 'GT', '19', '1908', 'San Diego'),
  ('Guatemala', 'GT', '19', '1909', 'La Unión'),
  ('Guatemala', 'GT', '19', '1910', 'Huité'),
  ('Guatemala', 'GT', '20', '2001', 'Chiquimula'),
  ('Guatemala', 'GT', '20', '2002', 'San José La Arada'),
  ('Guatemala', 'GT', '20', '2003', 'San Juan La Ermita'),
  ('Guatemala', 'GT', '20', '2004', 'Jocotán'),
  ('Guatemala', 'GT', '20', '2005', 'Camotán'),
  ('Guatemala', 'GT', '20', '2006', 'Olopa'),
  ('Guatemala', 'GT', '20', '2007', 'Esquipulas'),
  ('Guatemala', 'GT', '20', '2008', 'Concepción Las Minas'),
  ('Guatemala', 'GT', '20', '2009', 'Quezaltepeque'),
  ('Guatemala', 'GT', '20', '2010', 'San Jacinto'),
  ('Guatemala', 'GT', '20', '2011', 'Ipala'),
  ('Guatemala', 'GT', '21', '2101', 'Jalapa'),
  ('Guatemala', 'GT', '21', '2102', 'San Pedro Pinula'),
  ('Guatemala', 'GT', '21', '2103', 'San Luis Jilotepeque'),
  ('Guatemala', 'GT', '21', '2104', 'San Manuel Chaparrón'),
  ('Guatemala', 'GT', '21', '2105', 'San Carlos Alzatate'),
  ('Guatemala', 'GT', '21', '2106', 'Monjas'),
  ('Guatemala', 'GT', '21', '2107', 'Mataquescuintla'),
  ('Guatemala', 'GT', '22', '2201', 'Jutiapa'),
  ('Guatemala', 'GT', '22', '2202', 'El Progreso'),
  ('Guatemala', 'GT', '22', '2203', 'Santa Catarina Mita'),
  ('Guatemala', 'GT', '22', '2204', 'Agua Blanca'),
  ('Guatemala', 'GT', '22', '2205', 'Asunción Mita'),
  ('Guatemala', 'GT', '22', '2206', 'Yupiltepeque'),
  ('Guatemala', 'GT', '22', '2207', 'Atescatempa'),
  ('Guatemala', 'GT', '22', '2208', 'Jerez'),
  ('Guatemala', 'GT', '22', '2209', 'El Adelanto'),
  ('Guatemala', 'GT', '22', '2210', 'Zapotitlán'),
  ('Guatemala', 'GT', '22', '2211', 'Comapa'),
  ('Guatemala', 'GT', '22', '2212', 'Jalpatagua'),
  ('Guatemala', 'GT', '22', '2213', 'Conguaco'),
  ('Guatemala', 'GT', '22', '2214', 'Moyuta'),
  ('Guatemala', 'GT', '22', '2215', 'Pasaco'),
  ('Guatemala', 'GT', '22', '2216', 'San José Acatempa'),
  ('Guatemala', 'GT', '22', '2217', 'Quesada'),
  ('El Salvador', 'SV', '01', '0101', 'Ahuachapán'),
  ('El Salvador', 'SV', '01', '0102', 'Apaneca'),
  ('El Salvador', 'SV', '01', '0103', 'Atiquizaya'),
  ('El Salvador', 'SV', '01', '0104', 'Concepción de Ataco'),
  ('El Salvador', 'SV', '01', '0105', 'El Refugio'),
  ('El Salvador', 'SV', '01', '0106', 'Guaymango'),
  ('El Salvador', 'SV', '01', '0107', 'Jujutla'),
  ('El Salvador', 'SV', '01', '0108', 'San Francisco Menéndez'),
  ('El Salvador', 'SV', '01', '0109', 'San Lorenzo'),
  ('El Salvador', 'SV', '01', '0110', 'San Pedro Puxtla'),
  ('El Salvador', 'SV', '01', '0111', 'Tacuba'),
  ('El Salvador', 'SV', '01', '0112', 'Turín'),
  ('El Salvador', 'SV', '02', '0201', 'Candelaria de la Frontera'),
  ('El Salvador', 'SV', '02', '0202', 'Coatepeque'),
  ('El Salvador', 'SV', '02', '0203', 'Chalchuapa'),
  ('El Salvador', 'SV', '02', '0204', 'El Congo'),
  ('El Salvador', 'SV', '02', '0205', 'El Porvenir'),
  ('El Salvador', 'SV', '02', '0206', 'Masahuat'),
  ('El Salvador', 'SV', '02', '0207', 'Metapán'),
  ('El Salvador', 'SV', '02', '0208', 'San Antonio Pajonal'),
  ('El Salvador', 'SV', '02', '0209', 'San Sebastián Salitrillo'),
  ('El Salvador', 'SV', '02', '0210', 'Santa Ana'),
  ('El Salvador', 'SV', '02', '0211', 'Santa Rosa Guachipilín'),
  ('El Salvador', 'SV', '02', '0212', 'Santiago de la Frontera'),
  ('El Salvador', 'SV', '02', '0213', 'Texistepeque'),
  ('El Salvador', 'SV', '03', '0301', 'Acajutla'),
  ('El Salvador', 'SV', '03', '0302', 'Armenia'),
  ('El Salvador', 'SV', '03', '0303', 'Caluco'),
  ('El Salvador', 'SV', '03', '0304', 'Cuisnahuat'),
  ('El Salvador', 'SV', '03', '0305', 'Santa Isabel Ishuatán'),
  ('El Salvador', 'SV', '03', '0306', 'Izalco'),
  ('El Salvador', 'SV', '03', '0307', 'Juayúa'),
  ('El Salvador', 'SV', '03', '0308', 'Nahuizalco'),
  ('El Salvador', 'SV', '03', '0309', 'Nahulingo'),
  ('El Salvador', 'SV', '03', '0310', 'Salcoatitán'),
  ('El Salvador', 'SV', '03', '0311', 'San Antonio del Monte'),
  ('El Salvador', 'SV', '03', '0312', 'San Julián'),
  ('El Salvador', 'SV', '03', '0313', 'Santa Catarina Masahuat'),
  ('El Salvador', 'SV', '03', '0314', 'Santo Domingo de Guzmán'),
  ('El Salvador', 'SV', '03', '0315', 'Sonsonate'),
  ('El Salvador', 'SV', '03', '0316', 'Sonzacate'),
  ('El Salvador', 'SV', '04', '0401', 'Agua Caliente'),
  ('El Salvador', 'SV', '04', '0402', 'Arcatao'),
  ('El Salvador', 'SV', '04', '0403', 'Azacualpa'),
  ('El Salvador', 'SV', '04', '0404', 'Citalá'),
  ('El Salvador', 'SV', '04', '0405', 'Comalapa'),
  ('El Salvador', 'SV', '04', '0406', 'Concepción Quezaltepeque'),
  ('El Salvador', 'SV', '04', '0407', 'Chalatenango'),
  ('El Salvador', 'SV', '04', '0408', 'Dulce Nombre de María'),
  ('El Salvador', 'SV', '04', '0409', 'El Carrizal'),
  ('El Salvador', 'SV', '04', '0410', 'El Paraíso'),
  ('El Salvador', 'SV', '04', '0411', 'La Laguna'),
  ('El Salvador', 'SV', '04', '0412', 'La Palma'),
  ('El Salvador', 'SV', '04', '0413', 'La Reina'),
  ('El Salvador', 'SV', '04', '0414', 'Las Vueltas'),
  ('El Salvador', 'SV', '04', '0415', 'Nombre de Jesús'),
  ('El Salvador', 'SV', '04', '0416', 'Nueva Concepción'),
  ('El Salvador', 'SV', '04', '0417', 'Nueva Trinidad'),
  ('El Salvador', 'SV', '04', '0418', 'Ojos de Agua'),
  ('El Salvador', 'SV', '04', '0419', 'Potonico'),
  ('El Salvador', 'SV', '04', '0420', 'San Antonio de la Cruz'),
  ('El Salvador', 'SV', '04', '0421', 'San Antonio Los Ranchos'),
  ('El Salvador', 'SV', '04', '0422', 'San Fernando'),
  ('El Salvador', 'SV', '04', '0423', 'San Francisco Lempa'),
  ('El Salvador', 'SV', '04', '0424', 'San Francisco Morazán'),
  ('El Salvador', 'SV', '04', '0425', 'San Ignacio'),
  ('El Salvador', 'SV', '04', '0426', 'San Isidro Labrador'),
  ('El Salvador', 'SV', '04', '0427', 'San José Cancasque'),
  ('El Salvador', 'SV', '04', '0428', 'San José Las Flores'),
  ('El Salvador', 'SV', '04', '0429', 'San Luis del Carmen'),
  ('El Salvador', 'SV', '04', '0430', 'San Miguel de Mercedes'),
  ('El Salvador', 'SV', '04', '0431', 'San Rafael'),
  ('El Salvador', 'SV', '04', '0432', 'Santa Rita'),
  ('El Salvador', 'SV', '04', '0433', 'Tejutla'),
  ('El Salvador', 'SV', '05', '0501', 'Antiguo Cuscatlán'),
  ('El Salvador', 'SV', '05', '0502', 'Ciudad Arce'),
  ('El Salvador', 'SV', '05', '0503', 'Colón'),
  ('El Salvador', 'SV', '05', '0504', 'Comasagua'),
  ('El Salvador', 'SV', '05', '0505', 'Chiltiupán'),
  ('El Salvador', 'SV', '05', '0506', 'Huizúcar'),
  ('El Salvador', 'SV', '05', '0507', 'Jayaque'),
  ('El Salvador', 'SV', '05', '0508', 'Jicalapa'),
  ('El Salvador', 'SV', '05', '0509', 'La Libertad'),
  ('El Salvador', 'SV', '05', '0510', 'Nuevo Cuscatlán'),
  ('El Salvador', 'SV', '05', '0511', 'Santa Tecla'),
  ('El Salvador', 'SV', '05', '0512', 'Quezaltepeque'),
  ('El Salvador', 'SV', '05', '0513', 'Sacacoyo'),
  ('El Salvador', 'SV', '05', '0514', 'San José Villanueva'),
  ('El Salvador', 'SV', '05', '0515', 'San Juan Opico'),
  ('El Salvador', 'SV', '05', '0516', 'San Matías'),
  ('El Salvador', 'SV', '05', '0517', 'San Pablo Tacachico'),
  ('El Salvador', 'SV', '05', '0518', 'Tamanique'),
  ('El Salvador', 'SV', '05', '0519', 'Talnique'),
  ('El Salvador', 'SV', '05', '0520', 'Teotepeque'),
  ('El Salvador', 'SV', '05', '0521', 'Tepecoyo'),
  ('El Salvador', 'SV', '05', '0522', 'Zaragoza'),
  ('El Salvador', 'SV', '06', '0601', 'Aguilares'),
  ('El Salvador', 'SV', '06', '0602', 'Apopa'),
  ('El Salvador', 'SV', '06', '0603', 'Ayutuxtepeque'),
  ('El Salvador', 'SV', '06', '0604', 'Cuscatancingo'),
  ('El Salvador', 'SV', '06', '0605', 'El Paisnal'),
  ('El Salvador', 'SV', '06', '0606', 'Guazapa'),
  ('El Salvador', 'SV', '06', '0607', 'Ilopango'),
  ('El Salvador', 'SV', '06', '0608', 'Mejicanos'),
  ('El Salvador', 'SV', '06', '0609', 'Nejapa'),
  ('El Salvador', 'SV', '06', '0610', 'Panchimalco'),
  ('El Salvador', 'SV', '06', '0611', 'Rosario de Mora'),
  ('El Salvador', 'SV', '06', '0612', 'San Marcos'),
  ('El Salvador', 'SV', '06', '0613', 'San Martín'),
  ('El Salvador', 'SV', '06', '0614', 'San Salvador'),
  ('El Salvador', 'SV', '06', '0615', 'Santiago Texacuangos'),
  ('El Salvador', 'SV', '06', '0616', 'Santo Tomás'),
  ('El Salvador', 'SV', '06', '0617', 'Soyapango'),
  ('El Salvador', 'SV', '06', '0618', 'Tonacatepeque'),
  ('El Salvador', 'SV', '06', '0619', 'Ciudad Delgado'),
  ('El Salvador', 'SV', '07', '0701', 'Candelaria'),
  ('El Salvador', 'SV', '07', '0702', 'Cojutepeque'),
  ('El Salvador', 'SV', '07', '0703', 'El Carmen'),
  ('El Salvador', 'SV', '07', '0704', 'El Rosario'),
  ('El Salvador', 'SV', '07', '0705', 'Monte San Juan'),
  ('El Salvador', 'SV', '07', '0706', 'Oratorio de Concepción'),
  ('El Salvador', 'SV', '07', '0707', 'San Bartolomé Perulapía'),
  ('El Salvador', 'SV', '07', '0708', 'San Cristóbal'),
  ('El Salvador', 'SV', '07', '0709', 'San José Guayabal'),
  ('El Salvador', 'SV', '07', '0710', 'San Pedro Perulapán'),
  ('El Salvador', 'SV', '07', '0711', 'San Rafael Cedros'),
  ('El Salvador', 'SV', '07', '0712', 'San Ramón'),
  ('El Salvador', 'SV', '07', '0713', 'Santa Cruz Analquito'),
  ('El Salvador', 'SV', '07', '0714', 'Santa Cruz Michapa'),
  ('El Salvador', 'SV', '07', '0715', 'Suchitoto'),
  ('El Salvador', 'SV', '07', '0716', 'Tenancingo'),
  ('El Salvador', 'SV', '08', '0801', 'Cuyultitán'),
  ('El Salvador', 'SV', '08', '0802', 'Rosario de La Paz'),
  ('El Salvador', 'SV', '08', '0803', 'Jerusalén'),
  ('El Salvador', 'SV', '08', '0804', 'Mercedes La Ceiba'),
  ('El Salvador', 'SV', '08', '0805', 'Olocuilta'),
  ('El Salvador', 'SV', '08', '0806', 'Paraíso de Osorio'),
  ('El Salvador', 'SV', '08', '0807', 'San Antonio Masahuat'),
  ('El Salvador', 'SV', '08', '0808', 'San Emigdio'),
  ('El Salvador', 'SV', '08', '0809', 'San Francisco Chinameca'),
  ('El Salvador', 'SV', '08', '0810', 'San Juan Nonualco'),
  ('El Salvador', 'SV', '08', '0811', 'San Juan Talpa'),
  ('El Salvador', 'SV', '08', '0812', 'San Juan Tepezontes'),
  ('El Salvador', 'SV', '08', '0813', 'San Luis Talpa'),
  ('El Salvador', 'SV', '08', '0814', 'San Miguel Tepezontes'),
  ('El Salvador', 'SV', '08', '0815', 'San Pedro Masahuat'),
  ('El Salvador', 'SV', '08', '0816', 'San Pedro Nonualco'),
  ('El Salvador', 'SV', '08', '0817', 'San Rafael Obrajuelo'),
  ('El Salvador', 'SV', '08', '0818', 'Santa María Ostuma'),
  ('El Salvador', 'SV', '08', '0819', 'Santiago Nonualco'),
  ('El Salvador', 'SV', '08', '0820', 'Tapalhuaca'),
  ('El Salvador', 'SV', '08', '0821', 'Zacatecoluca'),
  ('El Salvador', 'SV', '08', '0822', 'San Luis La Herradura'),
  ('El Salvador', 'SV', '09', '0901', 'Cinquera'),
  ('El Salvador', 'SV', '09', '0902', 'Guacotecti'),
  ('El Salvador', 'SV', '09', '0903', 'Ilobasco'),
  ('El Salvador', 'SV', '09', '0904', 'Jutiapa'),
  ('El Salvador', 'SV', '09', '0905', 'San Isidro'),
  ('El Salvador', 'SV', '09', '0906', 'Sensuntepeque'),
  ('El Salvador', 'SV', '09', '0907', 'Tejutepeque'),
  ('El Salvador', 'SV', '09', '0908', 'Victoria'),
  ('El Salvador', 'SV', '09', '0909', 'Dolores'),
  ('El Salvador', 'SV', '10', '1001', 'Apastepeque'),
  ('El Salvador', 'SV', '10', '1002', 'Guadalupe'),
  ('El Salvador', 'SV', '10', '1003', 'San Cayetano Istepeque'),
  ('El Salvador', 'SV', '10', '1004', 'Santa Clara'),
  ('El Salvador', 'SV', '10', '1005', 'Santo Domingo'),
  ('El Salvador', 'SV', '10', '1006', 'San Esteban Catarina'),
  ('El Salvador', 'SV', '10', '1007', 'San Ildefonso'),
  ('El Salvador', 'SV', '10', '1008', 'San Lorenzo'),
  ('El Salvador', 'SV', '10', '1009', 'San Sebastián'),
  ('El Salvador', 'SV', '10', '1010', 'San Vicente'),
  ('El Salvador', 'SV', '10', '1011', 'Tecoluca'),
  ('El Salvador', 'SV', '10', '1012', 'Tepetitán'),
  ('El Salvador', 'SV', '10', '1013', 'Verapaz'),
  ('El Salvador', 'SV', '11', '1101', 'Alegría'),
  ('El Salvador', 'SV', '11', '1102', 'Berlín'),
  ('El Salvador', 'SV', '11', '1103', 'California'),
  ('El Salvador', 'SV', '11', '1104', 'Concepción Batres'),
  ('El Salvador', 'SV', '11', '1105', 'El Triunfo'),
  ('El Salvador', 'SV', '11', '1106', 'Ereguayquín'),
  ('El Salvador', 'SV', '11', '1107', 'Estanzuelas'),
  ('El Salvador', 'SV', '11', '1108', 'Jiquilisco'),
  ('El Salvador', 'SV', '11', '1109', 'Jucuapa'),
  ('El Salvador', 'SV', '11', '1110', 'Jucuarán'),
  ('El Salvador', 'SV', '11', '1111', 'Mercedes Umaña'),
  ('El Salvador', 'SV', '11', '1112', 'Nueva Granada'),
  ('El Salvador', 'SV', '11', '1113', 'Ozatlán'),
  ('El Salvador', 'SV', '11', '1114', 'Puerto El Triunfo'),
  ('El Salvador', 'SV', '11', '1115', 'San Agustín'),
  ('El Salvador', 'SV', '11', '1116', 'San Buenaventura'),
  ('El Salvador', 'SV', '11', '1117', 'San Dionisio'),
  ('El Salvador', 'SV', '11', '1118', 'Santa Elena'),
  ('El Salvador', 'SV', '11', '1119', 'San Francisco Javier'),
  ('El Salvador', 'SV', '11', '1120', 'Santa María'),
  ('El Salvador', 'SV', '11', '1121', 'Santiago de María'),
  ('El Salvador', 'SV', '11', '1122', 'Tecapán'),
  ('El Salvador', 'SV', '11', '1123', 'Usulután'),
  ('El Salvador', 'SV', '12', '1201', 'Carolina'),
  ('El Salvador', 'SV', '12', '1202', 'Ciudad Barrios'),
  ('El Salvador', 'SV', '12', '1203', 'Comacarán'),
  ('El Salvador', 'SV', '12', '1204', 'Chapeltique'),
  ('El Salvador', 'SV', '12', '1205', 'Chinameca'),
  ('El Salvador', 'SV', '12', '1206', 'Chirilagua'),
  ('El Salvador', 'SV', '12', '1207', 'El Tránsito'),
  ('El Salvador', 'SV', '12', '1208', 'Lolotique'),
  ('El Salvador', 'SV', '12', '1209', 'Moncagua'),
  ('El Salvador', 'SV', '12', '1210', 'Nueva Guadalupe'),
  ('El Salvador', 'SV', '12', '1211', 'Nuevo Edén de San Juan'),
  ('El Salvador', 'SV', '12', '1212', 'Quelepa'),
  ('El Salvador', 'SV', '12', '1213', 'San Antonio del Mosco'),
  ('El Salvador', 'SV', '12', '1214', 'San Gerardo'),
  ('El Salvador', 'SV', '12', '1215', 'San Jorge'),
  ('El Salvador', 'SV', '12', '1216', 'San Luis de la Reina'),
  ('El Salvador', 'SV', '12', '1217', 'San Miguel'),
  ('El Salvador', 'SV', '12', '1218', 'San Rafael Oriente'),
  ('El Salvador', 'SV', '12', '1219', 'Sesori'),
  ('El Salvador', 'SV', '12', '1220', 'Uluazapa'),
  ('El Salvador', 'SV', '13', '1301', 'Arambala'),
  ('El Salvador', 'SV', '13', '1302', 'Cacaopera'),
  ('El Salvador', 'SV', '13', '1303', 'Corinto'),
  ('El Salvador', 'SV', '13', '1304', 'Chilanga'),
  ('El Salvador', 'SV', '13', '1305', 'Delicias de Concepción'),
  ('El Salvador', 'SV', '13', '1306', 'El Divisadero'),
  ('El Salvador', 'SV', '13', '1307', 'El Rosario'),
  ('El Salvador', 'SV', '13', '1308', 'Gualococti'),
  ('El Salvador', 'SV', '13', '1309', 'Guatajiagua'),
  ('El Salvador', 'SV', '13', '1310', 'Joateca'),
  ('El Salvador', 'SV', '13', '1311', 'Jocoaitique'),
  ('El Salvador', 'SV', '13', '1312', 'Jocoro'),
  ('El Salvador', 'SV', '13', '1313', 'Lolotiquillo'),
  ('El Salvador', 'SV', '13', '1314', 'Meanguera'),
  ('El Salvador', 'SV', '13', '1315', 'Osicala'),
  ('El Salvador', 'SV', '13', '1316', 'Perquín'),
  ('El Salvador', 'SV', '13', '1317', 'San Carlos'),
  ('El Salvador', 'SV', '13', '1318', 'San Fernando'),
  ('El Salvador', 'SV', '13', '1319', 'San Francisco Gotera'),
  ('El Salvador', 'SV', '13', '1320', 'San Isidro'),
  ('El Salvador', 'SV', '13', '1321', 'San Simón'),
  ('El Salvador', 'SV', '13', '1322', 'Sensembra'),
  ('El Salvador', 'SV', '13', '1323', 'Sociedad'),
  ('El Salvador', 'SV', '13', '1324', 'Torola'),
  ('El Salvador', 'SV', '13', '1325', 'Yamabal'),
  ('El Salvador', 'SV', '13', '1326', 'Yoloaiquín'),
  ('El Salvador', 'SV', '14', '1401', 'Anamorós'),
  ('El Salvador', 'SV', '14', '1402', 'Bolívar'),
  ('El Salvador', 'SV', '14', '1403', 'Concepción de Oriente'),
  ('El Salvador', 'SV', '14', '1404', 'Conchagua'),
  ('El Salvador', 'SV', '14', '1405', 'El Carmen'),
  ('El Salvador', 'SV', '14', '1406', 'El Sauce'),
  ('El Salvador', 'SV', '14', '1407', 'Intipucá'),
  ('El Salvador', 'SV', '14', '1408', 'La Unión'),
  ('El Salvador', 'SV', '14', '1409', 'Lislique'),
  ('El Salvador', 'SV', '14', '1410', 'Meanguera del Golfo'),
  ('El Salvador', 'SV', '14', '1411', 'Nueva Esparta'),
  ('El Salvador', 'SV', '14', '1412', 'Pasaquina'),
  ('El Salvador', 'SV', '14', '1413', 'Polorós'),
  ('El Salvador', 'SV', '14', '1414', 'San Alejo'),
  ('El Salvador', 'SV', '14', '1415', 'San José'),
  ('El Salvador', 'SV', '14', '1416', 'Santa Rosa de Lima'),
  ('El Salvador', 'SV', '14', '1417', 'Yayantique'),
  ('El Salvador', 'SV', '14', '1418', 'Yucuaiquín')
on conflict (pais, codigo_municipio) do update set
  codigo_pais = excluded.codigo_pais,
  codigo_departamento = excluded.codigo_departamento,
  municipio = excluded.municipio,
  actualizado_en = now();

create index if not exists catalogo_ubicacion_municipio_departamento_idx
  on public.catalogo_ubicacion_municipio (pais, codigo_departamento, municipio);

alter table public.catalogo_ubicacion_departamento enable row level security;
alter table public.catalogo_ubicacion_municipio enable row level security;

drop policy if exists catalogo_ubicacion_departamento_deny_anon on public.catalogo_ubicacion_departamento;
create policy catalogo_ubicacion_departamento_deny_anon
  on public.catalogo_ubicacion_departamento for all to anon using (false) with check (false);
drop policy if exists catalogo_ubicacion_departamento_deny_authenticated on public.catalogo_ubicacion_departamento;
create policy catalogo_ubicacion_departamento_deny_authenticated
  on public.catalogo_ubicacion_departamento for all to authenticated using (false) with check (false);

drop policy if exists catalogo_ubicacion_municipio_deny_anon on public.catalogo_ubicacion_municipio;
create policy catalogo_ubicacion_municipio_deny_anon
  on public.catalogo_ubicacion_municipio for all to anon using (false) with check (false);
drop policy if exists catalogo_ubicacion_municipio_deny_authenticated on public.catalogo_ubicacion_municipio;
create policy catalogo_ubicacion_municipio_deny_authenticated
  on public.catalogo_ubicacion_municipio for all to authenticated using (false) with check (false);

revoke all on table public.catalogo_ubicacion_departamento from anon, authenticated;
revoke all on table public.catalogo_ubicacion_municipio from anon, authenticated;

comment on table public.catalogo_ubicacion_departamento is
  'Catalogo compartido de departamentos usado por formularios EntoNet.';
comment on table public.catalogo_ubicacion_municipio is
  'Catalogo compartido de municipios usado por formularios EntoNet.';

commit;
