begin;

create extension if not exists pgcrypto;

create table if not exists public.encuesta_sat26_intake (
  intake_id bigint generated by default as identity primary key,

  encuesta_codigo text not null default 'SAT26',
  encuesta_nombre text not null default 'Encuesta SAT26',
  formulario_version text,

  review_status text not null default 'pending'
    check (review_status in ('pending', 'reviewed', 'rejected')),
  review_notes text,
  reviewed_by text,
  reviewed_at timestamptz,

  submission_token uuid not null default gen_random_uuid(),
  submitted_at timestamptz not null default now(),
  source_url text,
  respondent_ip inet,
  user_agent text,

  payload jsonb not null,

  creado_por text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create unique index if not exists encuesta_sat26_submission_token_idx
  on public.encuesta_sat26_intake (submission_token);

create index if not exists encuesta_sat26_review_status_idx
  on public.encuesta_sat26_intake (review_status, creado_en desc);

create index if not exists encuesta_sat26_submitted_at_idx
  on public.encuesta_sat26_intake (submitted_at desc);

create index if not exists encuesta_sat26_payload_gin_idx
  on public.encuesta_sat26_intake using gin (payload);

alter table public.encuesta_sat26_intake enable row level security;

drop policy if exists encuesta_sat26_deny_authenticated
  on public.encuesta_sat26_intake;
create policy encuesta_sat26_deny_authenticated
  on public.encuesta_sat26_intake
  for all to authenticated
  using (false)
  with check (false);

drop policy if exists encuesta_sat26_public_insert
  on public.encuesta_sat26_intake;
create policy encuesta_sat26_public_insert
  on public.encuesta_sat26_intake
  for insert to anon
  with check (true);

drop policy if exists encuesta_sat26_deny_select_anon
  on public.encuesta_sat26_intake;
create policy encuesta_sat26_deny_select_anon
  on public.encuesta_sat26_intake
  for select to anon
  using (false);

grant insert on table public.encuesta_sat26_intake to anon;
revoke all on table public.encuesta_sat26_intake from authenticated;
revoke all on sequence public.encuesta_sat26_intake_intake_id_seq from anon, authenticated;

comment on table public.encuesta_sat26_intake is
  'Captura de respuestas de la Encuesta SAT26 desde el sitio de EntoNet.';

commit;
