begin;

create table if not exists public.formulario_7_sinergista_intake (
  sinergista_intake_id bigint generated by default as identity primary key,
  review_status text not null default 'pending'
    check (review_status in ('pending', 'reviewed', 'rejected')),
  review_notes text,
  reviewed_by text,
  reviewed_at timestamptz,
  version_estructura text not null default 'f7_sinergistas_v1',
  formulario_codigo text not null default 'F7' check (formulario_codigo = 'F7'),
  formulario_nombre text not null default 'Registro de datos del bioensayo de la botella CDC',
  fecha_registro date not null default current_date,
  codigo_bioensayo text not null,
  nombre_poblacion text not null,
  pais text not null check (pais in ('El Salvador', 'Guatemala')),
  id_institucion text not null default 'UVG',
  codigo_departamento text not null,
  codigo_municipio text not null,
  sinergista_tipo text not null check (sinergista_tipo in ('DEF', 'PBO', 'DM')),
  dosis_sinergista_ug_ml numeric not null check (dosis_sinergista_ug_ml >= 0),
  sinergista_resultado_diagnostico text
    check (sinergista_resultado_diagnostico is null or sinergista_resultado_diagnostico in ('Susceptible', 'Sospecha de Resistencia', 'Resistente', 'Ensayo inválido')),
  etanol_resultado_diagnostico text
    check (etanol_resultado_diagnostico is null or etanol_resultado_diagnostico in ('Susceptible', 'Sospecha de Resistencia', 'Resistente', 'Ensayo inválido')),
  sinergista_mortalidad_corregida_pct numeric check (sinergista_mortalidad_corregida_pct is null or sinergista_mortalidad_corregida_pct between 0 and 100),
  etanol_mortalidad_corregida_pct numeric check (etanol_mortalidad_corregida_pct is null or etanol_mortalidad_corregida_pct between 0 and 100),
  sinergista_mortalidad_control_pct numeric check (sinergista_mortalidad_control_pct is null or sinergista_mortalidad_control_pct between 0 and 100),
  etanol_mortalidad_control_pct numeric check (etanol_mortalidad_control_pct is null or etanol_mortalidad_control_pct between 0 and 100),
  incluir_24h boolean not null default false,
  fecha_realizacion_bioensayo date not null,
  insecticida text not null,
  solvente_utilizado text not null check (solvente_utilizado in ('Etanol', 'Otro')),
  solvente_otro text,
  dosis_intensidad_ug_ml numeric not null check (dosis_intensidad_ug_ml >= 0),
  lote_insecticida text not null,
  fecha_revestimiento_botellas date not null,
  numero_usos_botella_e1 integer check (numero_usos_botella_e1 >= 0),
  numero_usos_botella_e2 integer check (numero_usos_botella_e2 >= 0),
  numero_usos_botella_e3 integer check (numero_usos_botella_e3 >= 0),
  numero_usos_botella_e4 integer check (numero_usos_botella_e4 >= 0),
  numero_usos_botella_c1 integer check (numero_usos_botella_c1 >= 0),
  origen_material text not null check (origen_material in ('Silvestre', 'Laboratorio')),
  edad_dias integer check (edad_dias >= 0),
  edad_indefinida boolean not null default false,
  codigo_especie_mosquito text not null,
  fecha_separacion date not null,
  hora_separacion time not null,
  generacion_filial text,
  generacion_filial_indefinida boolean not null default false,
  codigo_responsable_revestimiento text not null,
  codigo_responsable_bioensayo text not null,
  codigo_control_calidad text not null default 'NO APLICA',
  codigo_revision_24h text,
  temperatura_inicial_c numeric not null,
  temperatura_final_c numeric not null,
  humedad_relativa_inicial_pct numeric not null check (humedad_relativa_inicial_pct between 0 and 100),
  humedad_relativa_final_pct numeric not null check (humedad_relativa_final_pct between 0 and 100),
  hora_inicio_bioensayo time not null,
  hora_final_bioensayo time not null,
  fuente_formulario text,
  nombre_quien_ingreso text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint formulario_7_sinergista_codigo_unique unique (codigo_bioensayo),
  constraint formulario_7_sinergista_solvente_consistente check (
    (solvente_utilizado = 'Etanol' and nullif(btrim(solvente_otro), '') is null)
    or (solvente_utilizado = 'Otro' and nullif(btrim(solvente_otro), '') is not null)
  ),
  constraint formulario_7_sinergista_edad_consistente check (
    (edad_indefinida and edad_dias is null)
    or (not edad_indefinida and edad_dias is not null)
  ),
  constraint formulario_7_sinergista_generacion_consistente check (
    (generacion_filial_indefinida and nullif(btrim(generacion_filial), '') is null)
    or (not generacion_filial_indefinida and nullif(btrim(generacion_filial), '') is not null)
  ),
  constraint formulario_7_sinergista_revision_24h_consistente check (
    (incluir_24h and nullif(btrim(codigo_revision_24h), '') is not null)
    or (not incluir_24h)
  )
);

create table if not exists public.formulario_7_sinergista_resultado_intake (
  sinergista_resultado_id bigint generated by default as identity primary key,
  sinergista_intake_id bigint not null references public.formulario_7_sinergista_intake(sinergista_intake_id) on delete cascade,
  tipo_set text not null check (tipo_set in ('sinergista', 'etanol')),
  etapa text not null check (etapa in ('pretratamiento', 'bioensayo', 'kdr_24h')),
  botella text not null check (botella in ('e1', 'e2', 'e3', 'e4', 'e5', 'c1')),
  tiempo_minutos integer not null check (tiempo_minutos in (0, 15, 30, 45, 60, 1440)),
  hora_inicio time,
  vivos integer not null check (vivos >= 0),
  incapacitados integer not null check (incapacitados >= 0),
  creado_en timestamptz not null default now(),
  unique (sinergista_intake_id, tipo_set, etapa, botella, tiempo_minutos),
  constraint formulario_7_sinergista_resultado_flujo_check check (
    (etapa = 'pretratamiento' and botella in ('e1', 'e2', 'e3', 'e4', 'e5') and tiempo_minutos = 60)
    or (etapa = 'bioensayo' and botella in ('e1', 'e2', 'e3', 'e4', 'c1') and tiempo_minutos in (0, 15, 30, 45))
    or (etapa = 'kdr_24h' and botella in ('e1', 'e2', 'e3', 'e4', 'c1') and tiempo_minutos = 1440)
  )
);

create table if not exists public.formulario_7_sinergista_comentario_intake (
  sinergista_comentario_id bigint generated by default as identity primary key,
  sinergista_intake_id bigint not null references public.formulario_7_sinergista_intake(sinergista_intake_id) on delete cascade,
  comentario text,
  nombre text,
  sinergista_observaciones_pretratamiento text,
  sinergista_observaciones_bioensayo text,
  etanol_observaciones_pretratamiento text,
  etanol_observaciones_bioensayo text,
  creado_en timestamptz not null default now(),
  unique (sinergista_intake_id)
);

create index if not exists formulario_7_sinergista_review_status_idx
  on public.formulario_7_sinergista_intake (review_status, creado_en desc);
create index if not exists formulario_7_sinergista_fecha_idx
  on public.formulario_7_sinergista_intake (fecha_realizacion_bioensayo);
create index if not exists formulario_7_sinergista_institucion_idx
  on public.formulario_7_sinergista_intake (id_institucion);
create index if not exists formulario_7_sinergista_resultado_parent_idx
  on public.formulario_7_sinergista_resultado_intake (sinergista_intake_id);
create index if not exists formulario_7_sinergista_resultado_lookup_idx
  on public.formulario_7_sinergista_resultado_intake (tipo_set, etapa, botella, tiempo_minutos);
create index if not exists formulario_7_sinergista_comentario_parent_idx
  on public.formulario_7_sinergista_comentario_intake (sinergista_intake_id);

alter table public.formulario_7_sinergista_intake enable row level security;
alter table public.formulario_7_sinergista_resultado_intake enable row level security;
alter table public.formulario_7_sinergista_comentario_intake enable row level security;

drop policy if exists formulario_7_sinergista_deny_anon
  on public.formulario_7_sinergista_intake;
create policy formulario_7_sinergista_deny_anon
  on public.formulario_7_sinergista_intake for all to anon using (false) with check (false);

drop policy if exists formulario_7_sinergista_deny_authenticated
  on public.formulario_7_sinergista_intake;
create policy formulario_7_sinergista_deny_authenticated
  on public.formulario_7_sinergista_intake for all to authenticated using (false) with check (false);

drop policy if exists formulario_7_sinergista_resultado_deny_anon
  on public.formulario_7_sinergista_resultado_intake;
create policy formulario_7_sinergista_resultado_deny_anon
  on public.formulario_7_sinergista_resultado_intake for all to anon using (false) with check (false);

drop policy if exists formulario_7_sinergista_resultado_deny_authenticated
  on public.formulario_7_sinergista_resultado_intake;
create policy formulario_7_sinergista_resultado_deny_authenticated
  on public.formulario_7_sinergista_resultado_intake for all to authenticated using (false) with check (false);

drop policy if exists formulario_7_sinergista_comentario_deny_anon
  on public.formulario_7_sinergista_comentario_intake;
create policy formulario_7_sinergista_comentario_deny_anon
  on public.formulario_7_sinergista_comentario_intake for all to anon using (false) with check (false);

drop policy if exists formulario_7_sinergista_comentario_deny_authenticated
  on public.formulario_7_sinergista_comentario_intake;
create policy formulario_7_sinergista_comentario_deny_authenticated
  on public.formulario_7_sinergista_comentario_intake for all to authenticated using (false) with check (false);

revoke all on table public.formulario_7_sinergista_intake from anon, authenticated;
revoke all on table public.formulario_7_sinergista_resultado_intake from anon, authenticated;
revoke all on table public.formulario_7_sinergista_comentario_intake from anon, authenticated;

grant select, insert on table public.formulario_7_sinergista_intake to service_role;
grant select, insert on table public.formulario_7_sinergista_resultado_intake to service_role;
grant select, insert on table public.formulario_7_sinergista_comentario_intake to service_role;

do $$
declare
  seq_name text;
begin
  foreach seq_name in array array[
    pg_get_serial_sequence('public.formulario_7_sinergista_intake', 'sinergista_intake_id'),
    pg_get_serial_sequence('public.formulario_7_sinergista_resultado_intake', 'sinergista_resultado_id'),
    pg_get_serial_sequence('public.formulario_7_sinergista_comentario_intake', 'sinergista_comentario_id')
  ] loop
    if seq_name is not null then
      execute format('revoke all on sequence %s from anon, authenticated', seq_name);
      execute format('grant usage, select on sequence %s to service_role', seq_name);
    end if;
  end loop;
end $$;

create or replace function public.entonet_insert_formulario_7_sinergista(p_header jsonb, p_results jsonb, p_comments jsonb)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_claims text := current_setting('request.jwt.claims', true);
  v_header public.formulario_7_sinergista_intake%rowtype;
  v_intake_id bigint;
begin
  if coalesce(v_claims, '') = '' or coalesce(v_claims::jsonb ->> 'role', '') <> 'service_role' then
    raise exception 'Acceso restringido al servidor EntoNet' using errcode = '42501';
  end if;
  if p_header is null then raise exception 'El Formulario 7 Sinergistas está vacío'; end if;

  v_header := jsonb_populate_record(null::public.formulario_7_sinergista_intake, p_header);
  insert into public.formulario_7_sinergista_intake (
    review_status, review_notes, reviewed_by, reviewed_at, version_estructura,
    formulario_codigo, formulario_nombre, fecha_registro, codigo_bioensayo,
    nombre_poblacion, pais, id_institucion, codigo_departamento, codigo_municipio,
    sinergista_tipo, dosis_sinergista_ug_ml, sinergista_resultado_diagnostico,
    etanol_resultado_diagnostico, sinergista_mortalidad_corregida_pct,
    etanol_mortalidad_corregida_pct, sinergista_mortalidad_control_pct,
    etanol_mortalidad_control_pct, incluir_24h, fecha_realizacion_bioensayo,
    insecticida, solvente_utilizado, solvente_otro, dosis_intensidad_ug_ml,
    lote_insecticida, fecha_revestimiento_botellas, numero_usos_botella_e1,
    numero_usos_botella_e2, numero_usos_botella_e3, numero_usos_botella_e4,
    numero_usos_botella_c1, origen_material, edad_dias, edad_indefinida,
    codigo_especie_mosquito, fecha_separacion, hora_separacion, generacion_filial,
    generacion_filial_indefinida, codigo_responsable_revestimiento,
    codigo_responsable_bioensayo, codigo_control_calidad, codigo_revision_24h,
    temperatura_inicial_c, temperatura_final_c, humedad_relativa_inicial_pct,
    humedad_relativa_final_pct, hora_inicio_bioensayo, hora_final_bioensayo,
    fuente_formulario, nombre_quien_ingreso
  ) values (
    coalesce(v_header.review_status, 'pending'), v_header.review_notes,
    v_header.reviewed_by, v_header.reviewed_at,
    coalesce(v_header.version_estructura, 'f7_sinergistas_v1'),
    coalesce(v_header.formulario_codigo, 'F7'),
    coalesce(v_header.formulario_nombre, 'Registro de datos del bioensayo de la botella CDC'),
    coalesce(v_header.fecha_registro, current_date), v_header.codigo_bioensayo,
    v_header.nombre_poblacion, v_header.pais, coalesce(v_header.id_institucion, 'UVG'),
    v_header.codigo_departamento, v_header.codigo_municipio, v_header.sinergista_tipo,
    v_header.dosis_sinergista_ug_ml, v_header.sinergista_resultado_diagnostico,
    v_header.etanol_resultado_diagnostico, v_header.sinergista_mortalidad_corregida_pct,
    v_header.etanol_mortalidad_corregida_pct, v_header.sinergista_mortalidad_control_pct,
    v_header.etanol_mortalidad_control_pct, coalesce(v_header.incluir_24h, false),
    v_header.fecha_realizacion_bioensayo, v_header.insecticida, v_header.solvente_utilizado,
    v_header.solvente_otro, v_header.dosis_intensidad_ug_ml, v_header.lote_insecticida,
    v_header.fecha_revestimiento_botellas, v_header.numero_usos_botella_e1,
    v_header.numero_usos_botella_e2, v_header.numero_usos_botella_e3,
    v_header.numero_usos_botella_e4, v_header.numero_usos_botella_c1,
    v_header.origen_material, v_header.edad_dias, coalesce(v_header.edad_indefinida, false),
    v_header.codigo_especie_mosquito, v_header.fecha_separacion, v_header.hora_separacion,
    v_header.generacion_filial, coalesce(v_header.generacion_filial_indefinida, false),
    v_header.codigo_responsable_revestimiento, v_header.codigo_responsable_bioensayo,
    coalesce(v_header.codigo_control_calidad, 'NO APLICA'), v_header.codigo_revision_24h,
    v_header.temperatura_inicial_c, v_header.temperatura_final_c,
    v_header.humedad_relativa_inicial_pct, v_header.humedad_relativa_final_pct,
    v_header.hora_inicio_bioensayo, v_header.hora_final_bioensayo,
    v_header.fuente_formulario, v_header.nombre_quien_ingreso
  ) returning sinergista_intake_id into v_intake_id;

  if p_results is not null and jsonb_typeof(p_results) = 'array' and jsonb_array_length(p_results) > 0 then
    insert into public.formulario_7_sinergista_resultado_intake
      (sinergista_intake_id, tipo_set, etapa, botella, tiempo_minutos, hora_inicio, vivos, incapacitados)
    select v_intake_id, result.tipo_set, result.etapa, result.botella,
      result.tiempo_minutos, result.hora_inicio, result.vivos, result.incapacitados
    from jsonb_to_recordset(p_results) as result(
      tipo_set text, etapa text, botella text, tiempo_minutos integer,
      hora_inicio time, vivos integer, incapacitados integer
    );
  end if;

  if p_comments is not null and jsonb_typeof(p_comments) = 'array' and jsonb_array_length(p_comments) > 0 then
    insert into public.formulario_7_sinergista_comentario_intake (
      sinergista_intake_id, comentario, nombre, sinergista_observaciones_pretratamiento,
      sinergista_observaciones_bioensayo, etanol_observaciones_pretratamiento,
      etanol_observaciones_bioensayo
    )
    select v_intake_id, comment.comentario, comment.nombre,
      comment.sinergista_observaciones_pretratamiento,
      comment.sinergista_observaciones_bioensayo,
      comment.etanol_observaciones_pretratamiento,
      comment.etanol_observaciones_bioensayo
    from jsonb_to_recordset(p_comments) as comment(
      comentario text, nombre text, sinergista_observaciones_pretratamiento text,
      sinergista_observaciones_bioensayo text, etanol_observaciones_pretratamiento text,
      etanol_observaciones_bioensayo text
    );
  end if;

  return v_intake_id;
end;
$$;

revoke all on function public.entonet_insert_formulario_7_sinergista(jsonb, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.entonet_insert_formulario_7_sinergista(jsonb, jsonb, jsonb) to service_role;

comment on table public.formulario_7_sinergista_intake is
  'Encabezado de la nueva captura de Formulario 7 Sinergistas. Diagnostica e Intensidad permanecen en formulario_7_bioensayo_intake.';
comment on table public.formulario_7_sinergista_resultado_intake is
  'Lecturas atomicas de Formulario 7 Sinergistas por set, etapa, botella y tiempo.';
comment on table public.formulario_7_sinergista_comentario_intake is
  'Comentarios y observaciones asociadas a la captura de Formulario 7 Sinergistas.';
comment on function public.entonet_insert_formulario_7_sinergista(jsonb, jsonb, jsonb) is
  'Inserta transaccionalmente encabezado, lecturas y comentarios de Formulario 7 Sinergistas. Uso restringido a service_role.';

commit;
